[ build ]
  [[build.env]]
    name='BP_PHP_SERVER'
    value='nginx'

  [[ build.env ]]
    name='BP_PHP_WEB_DIR'
    value="public"

  [[ build.env ]]
    name='BP_PHP_ENABLE_HTTPS_REDIRECT'
    value='false'
