apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-buildpacks-demo
  labels:
    app: laravel-buildpacks-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-buildpacks-demo
  template:
    metadata:
      labels:
        app: laravel-buildpacks-demo
    spec:
      #automountServiceAccountToken: true
      containers:
      - name: fpm
        image: ghcr.io/tkak/laravel-buildpacks-demo:3c1eeb2ebc0ecfe89aa758f109ee35cc32c1731b
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: '8080'
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
        resources:
          requests:
            cpu: 100m
            memory: 800Mi
          limits:
            cpu: 200m
            memory: 800Mi
        volumeMounts:
        - name: dotenv
          readOnly: true
          mountPath: "/workspace/.env"
          subPath: .env
      volumes:
      - name: dotenv
        secret:
          secretName: dotenv
          
