apiVersion: v1
kind: Service
metadata:
  name: laravel-buildpacks-demo
  labels:
    name: laravel-buildpacks-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: laravel-buildpacks-demo
