name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v4.9.0
    - name: Build image
      run: |
        pack build --clear-cache --env=BP_LOG_LEVEL=DEBUG \
            ghcr.io/${{ github.actor }}/laravel-buildpacks-demo:${{ github.sha }} --buildpack paketo-buildpacks/php --builder paketobuildpacks/builder:full
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to Registry
      run: |
        docker push "ghcr.io/${{ github.actor }}/laravel-buildpacks-demo:${{ github.sha }}"
