name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v4.4.0
    - name: Build image
      uses: mamezou-tech/buildpacks-action@master
      with:
        image: "ghcr.io/${{ github.actor }}/laravel-buildpacks-demo/laravel-buildpacks-demo"
        tag: "${{ github.sha }}"
        builder: 'gcr.io/paketo-buildpacks/builder:base'
        buildpacks: 'paketo-buildpacks/php'
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to Registry
      run: |
        docker push "ghcr.io/${{ github.actor }}/laravel-buildpacks-demo/laravel-buildpacks-demo:${{ github.sha }}"
